#server
server: 
  port: 80
  servlet:
    context-path: /
    
#spring datasource
spring: 
  datasource: 
    url: jdbc:mysql:///db_blog_zero?serverTimezone=GMT%2B8&characterEncoding=UTF8
    username: root
    password: 123456
    
#spring mybatis
mybatis: 
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/blog/*.xml
  
logging:
  level:
    com.zero: DEBUG